### ISSUE TITLE
Create File

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Dev#25]
### Steps to reproduce

1. Not created the file with the Username and password standard user. http://prntscr.com/ci2dki
2. When you download OAR files with no sky http://prntscr.com/ci2gjx
3. Problems with walking, even on just created the region.

The video shows all https://www.youtube.com/watch?v=7qWX1qs4vC4&feature=youtu.be

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Server configuration

**Operating system**: Windows 7(32bit) Windows Server 2012(64bit) Ubuntu 14.04

**Web server:**

**Database:**

**Virtual Universe version:**

### Logs

Please make sure that Virtual Universe has made an log-file and include a link to it here

**Comment by emperorstarfinder** [comment]
Hi LifeGold,

The file for the system accounts will be found in the Data Directory where your grid server runs (assuming your running in grid mode and not starting from scratch)  Additionally you can reset the system account passwords via the following commands:

Governor = reset governor password
RealEstate Owner = reset realestate password
Banker Universe = reset banker password
Marketplace Universe = reset marketplace password

If it didnt already create the notecards this should resolve that

The OAR it appears as though you logged in with the time setting to night.  If you set your environmental setting to Midday in your viewer the sky should be there.  We are aware that there is an issue with this and are working on it.  Some OARs also are having issues because of how we handle them.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment]
I completely deleted all of the server and put the latest version, it does not create these files. about the paddle is bad because version 1.0.2 VirtualUniverse it loads fine.

**Comment by LifeGold** [comment]
@emperorstarfinder I completely deleted all of the server and put the latest version, it does not create these files. about the paddle is bad because version 1.0.2 VirtualUniverse it loads fine.

**Comment by emperorstarfinder** [comment]
I hope your using Version 1.0.2 to run your grid and the development version only internally.  Always use the stable version for your public grid so these issues to cause problems for your users.

There are some loading issues that we are aware of and are working on those.  Hopefully we will have them fixed tonight or tomorrow.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
We have a major fix upcoming that will fix this issue.  We expect this to be rolled into the repositories later in the day USA Eastern Standard Time

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
Closing as user reports issue resolved

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
