### ISSUE TITLE
Error messages after compilling - info inside

### ISSUE THREAD

**Issue by BogusCurry** [Virtual-Universe/Virtual-Dev#32]
Hello ;D
I have clone the actual version of vu-dev, have make sudo ./autobuild and have becomes this
http://paste.md-5.net/vobokifaqu.vbs

**My System**:
Linux Mint 18 x64 Mono  4.6.2 (Stable 4.6.2.7/08fd525 Mon Nov 14 12:30:00 UTC 2016) 

Ok, I know the rep is here very dev, but would say that I have found this bug ;D

Greetings
Bogus

**Comment by emperorstarfinder** [comment]
Good Afternoon,

The Virtual-Dev repository is for just these kinds of things.  While we are developing the next version, our users can test the development code locally (not in a production environment of course) and help locate bugs that need to be corrected before code is declared stable for the next version and is pushed to our Virtual-Universe repository which our stable release code.  This helps prevent bugs from getting into the stable release.

Always feel free to test the code and report bugs.  In this way we can find problems that we might not be seeing internally.

This bug may just be due to a missing piece that has not yet been pushed to the repository.  It probably will get pushed to the repository later tonight.

Emperor Starfinder
Founder
Chief Executive Officer
Core Developer
Governing Body Chair
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
Email: emperor@secondgalaxy.com

**Comment by BogusCurry** [comment]
all good ;D 

I would say only there is a bug ..

**Comment by NoahStarfinder** [comment]
Good evening,

This should now be corrected.  It appears that doing early morning commits and myself do not get along so well.  I missed an expected ; which appears to have broken the build thus causing your error.  Building tests locally do work now so you should be ok.  Let us know if it worked or didn't.

Noah Starfinder 
Governing Body Vice Chair (North America) 
Core Developer 
In-Galaxy Services and Features Developer 
Work Group Member 
Grid Architecture Development Work Group 
Second Galaxy Development Team 
Email: noah@secondgalaxy.com

**Comment by BogusCurry** [comment]
Good morning ;D

The fix is good ;D No more errors after compilling ;D

Greetings

Bogus
Founder of GridTalk.de

**Comment by NoahStarfinder** [comment]
User reports issue as resolved.  Therefore closing with many thanks for the report.

Noah Starfinder 
Governing Body Vice Chair (North America) 
Core Developer 
In-Galaxy Services and Features Developer 
Work Group Member 
Grid Architecture Development Work Group 
Second Galaxy Development Team 
Email: noah@secondgalaxy.com
